### ISSUE TITLE
Add GN.sublime-syntax

### ISSUE THREAD

**Issue by chaopeng** [eseidelGoogle/gn_sublime#5]
Not sure if Eric still use this account. Not sure if it breaks the Sublime Text Package if we also provide `GN.sublime-syntax` file.

I found this repo because I want to add highlight for [bat](https://github.com/sharkdp/bat?tab=readme-ov-file#adding-new-syntaxes--language-definitions). If you have same need. Feel free to use following `GN.sublime-syntax`. Just generated with [SublimeSyntaxConvertor](https://github.com/aziz/SublimeSyntaxConvertor)

```
%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: GN
file_extensions:
  - gn
  - gni
scope: source.gn
contexts:
  main:
    - match: \b(?:if|else)\b
      comment: keywords
      scope: keyword.control.gn
    - match: \b(?:true|false)\b
      comment: constants
      scope: constant.language.gn
    - match: \b\d+\.?(?:\d+)?\b
      comment: numbers
      scope: constant.numeric.gn
    - match: '\"[^\"]*\"'
      comment: double quoted string
      scope: string.quoted.double.gn
    - match: "#"
      comment: comment
      push:
        - meta_scope: comment.gn
        - match: $
          pop: true
    - match: (?:=|==|\+=|-=|\+|-)
      comment: operators
      scope: keyword.operator.gn
    - match: |-
        \b(?:action|action_foreach|bundle_data|copy|create_bundle|executable|group|loadable_module|shared_library|source_set|static_library|target
        )\b
      comment: targets
      scope: entity.name.tag.gn
    - match: |-
        \b(?:assert|config|declare_args|defined|exec_script|foreach|forward_variables_from|get_label_info|get_path_info|get_target_outputs|getenv|import|not_needed|pool|print|process_file_template|read_file|rebase_path|set_default_toolchain|set_defaults|set_sources_assignment_filter|split_list|string_replace|template|tool|toolchain|write_file
        )\b
      comment: functions
      scope: entity.name.function.gn
    - match: \b(?:current_cpu|current_os|current_toolchain|default_toolchain|host_cpu|host_os|invoker|python_path|root_build_dir|root_gen_dir|root_out_dir|target_cpu|target_gen_dir|target_name|target_os|target_out_dir)\b
      comment: predefined variables
      scope: variable.parameter.gn
    - match: \b(?:all_dependent_configs|allow_circular_includes_from|arflags|args|asmflags|assert_no_deps|bundle_contents_dir|bundle_deps_filter|bundle_executable_dir|bundle_plugins_dir|bundle_resources_dir|bundle_root_dir|cflags|cflags_c|cflags_cc|cflags_objc|cflags_objcc|check_includes|code_signing_args|code_signing_outputs|code_signing_script|code_signing_sources|complete_static_lib|configs|data|data_deps|defines|depfile|deps|friend|include_dirs|inputs|ldflags|lib_dirs|libs|output_dir|output_extension|output_name|output_prefix_override|outputs|partial_info_plist|pool|precompiled_header|precompiled_header_type|precompiled_source|product_type|public|public_configs|public_deps|response_file_contents|script|sources|test_application_name|testonly|visibility|write_runtime_deps|xcode_extra_attributes)\b
      comment: target variables
      scope: entity.other.attribute-name.gn
```
